// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoZBUKQeoc5bRyn33idE3d8mvHWotmh_4',
    appId: '1:887776342207:web:23b45c651f2da99bda560a',
    messagingSenderId: '887776342207',
    projectId: 'ucmmappapp',
    authDomain: 'ucmmappapp.firebaseapp.com',
    storageBucket: 'ucmmappapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSv-GokZnLIeON83vByVJabyUIqsEEByA',
    appId: '1:887776342207:android:4e0b4fc84955dd54da560a',
    messagingSenderId: '887776342207',
    projectId: 'ucmmappapp',
    storageBucket: 'ucmmappapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2YqKSJegYbWzPbMVLbMKaAGDbhXgPZiE',
    appId: '1:887776342207:ios:aac57fe71ade1d6eda560a',
    messagingSenderId: '887776342207',
    projectId: 'ucmmappapp',
    storageBucket: 'ucmmappapp.firebasestorage.app',
    androidClientId: '887776342207-v9aeboi0ng03nntpa0oogar4jrl5ai8t.apps.googleusercontent.com',
    iosClientId: '887776342207-35qnbltcap8hr64o1u57d7dqfk0qq057.apps.googleusercontent.com',
    iosBundleId: 'com.example.ucmMappApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2YqKSJegYbWzPbMVLbMKaAGDbhXgPZiE',
    appId: '1:887776342207:ios:aac57fe71ade1d6eda560a',
    messagingSenderId: '887776342207',
    projectId: 'ucmmappapp',
    storageBucket: 'ucmmappapp.firebasestorage.app',
    androidClientId: '887776342207-v9aeboi0ng03nntpa0oogar4jrl5ai8t.apps.googleusercontent.com',
    iosClientId: '887776342207-35qnbltcap8hr64o1u57d7dqfk0qq057.apps.googleusercontent.com',
    iosBundleId: 'com.example.ucmMappApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoZBUKQeoc5bRyn33idE3d8mvHWotmh_4',
    appId: '1:887776342207:web:da670ec5e503dbcada560a',
    messagingSenderId: '887776342207',
    projectId: 'ucmmappapp',
    authDomain: 'ucmmappapp.firebaseapp.com',
    storageBucket: 'ucmmappapp.firebasestorage.app',
  );
}
